/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  globals: {
    hero: Hero;
    about: About;
    'why-us': WhyUs;
    teachers: Teacher;
    subjects: Subject;
    contact: Contact;
    footer: Footer;
    register: Register;
    timetable: Timetable;
  };
  globalsSelect: {
    hero: HeroSelect<false> | HeroSelect<true>;
    about: AboutSelect<false> | AboutSelect<true>;
    'why-us': WhyUsSelect<false> | WhyUsSelect<true>;
    teachers: TeachersSelect<false> | TeachersSelect<true>;
    subjects: SubjectsSelect<false> | SubjectsSelect<true>;
    contact: ContactSelect<false> | ContactSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    register: RegisterSelect<false> | RegisterSelect<true>;
    timetable: TimetableSelect<false> | TimetableSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero".
 */
export interface Hero {
  id: string;
  description: string;
  metrics: {
    parents: number;
    students: number;
    subjects: number;
    tutors: number;
  };
  carousel?:
    | {
        image: string | Media;
        alt?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about".
 */
export interface About {
  id: string;
  title: string;
  description: string;
  featureImage: {
    image: string | Media;
    alt: string;
  };
  missionPoints: {
    card1: {
      title: string;
      shortDescription: string;
      longDescription: string;
    };
    card2: {
      title: string;
      shortDescription: string;
      longDescription: string;
    };
    card3: {
      title: string;
      shortDescription: string;
      longDescription: string;
    };
  };
  stats: {
    stat1: {
      value: string;
      label: string;
    };
    stat2: {
      value: string;
      label: string;
    };
    stat3: {
      value: string;
      label: string;
    };
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "why-us".
 */
export interface WhyUs {
  id: string;
  title: string;
  description: string;
  features: {
    feature1: {
      icon: 'sparkles' | 'target' | 'star' | 'clock' | 'check' | 'lightbulb';
      title: string;
      description: string;
      expandedContent: string;
    };
    feature2: {
      icon: 'sparkles' | 'target' | 'star' | 'clock' | 'check' | 'lightbulb';
      title: string;
      description: string;
      expandedContent: string;
    };
    feature3: {
      icon: 'sparkles' | 'target' | 'star' | 'clock' | 'check' | 'lightbulb';
      title: string;
      description: string;
      expandedContent: string;
    };
    feature4: {
      icon: 'sparkles' | 'target' | 'star' | 'clock' | 'check' | 'lightbulb';
      title: string;
      description: string;
      expandedContent: string;
    };
    feature5: {
      icon: 'sparkles' | 'target' | 'star' | 'clock' | 'check' | 'lightbulb';
      title: string;
      description: string;
      expandedContent: string;
    };
    feature6: {
      icon: 'sparkles' | 'target' | 'star' | 'clock' | 'check' | 'lightbulb';
      title: string;
      description: string;
      expandedContent: string;
    };
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "teachers".
 */
export interface Teacher {
  id: string;
  title: string;
  description: string;
  teachers?:
    | {
        name: string;
        title: string;
        description: string;
        subjects?:
          | {
              label: string;
              id?: string | null;
            }[]
          | null;
        photo: {
          image: string | Media;
          alt: string;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subjects".
 */
export interface Subject {
  id: string;
  title: string;
  description: string;
  categories?: {
    primary?: {
      subjects?:
        | {
            title: string;
            icon: 'book' | 'languages' | 'calculator' | 'atom' | 'globe' | 'code' | 'music' | 'palette';
            shortDescription: string;
            highlights?:
              | {
                  text: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
          }[]
        | null;
    };
    lowerSecondary?: {
      subjects?:
        | {
            title: string;
            icon: 'book' | 'languages' | 'calculator' | 'atom' | 'globe' | 'code' | 'music' | 'palette';
            shortDescription: string;
            highlights?:
              | {
                  text: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
          }[]
        | null;
    };
    upperSecondary?: {
      subjects?:
        | {
            title: string;
            icon: 'book' | 'languages' | 'calculator' | 'atom' | 'globe' | 'code' | 'music' | 'palette';
            shortDescription: string;
            highlights?:
              | {
                  text: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
          }[]
        | null;
    };
  };
  packages?:
    | {
        id: string;
        name: string;
        grade: string;
        price: number;
        subjects?:
          | {
              label: string;
              id?: string | null;
            }[]
          | null;
        popular?: boolean | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact".
 */
export interface Contact {
  id: string;
  title: string;
  description: string;
  contactInfo: {
    phone: string;
    email: string;
    location: string;
  };
  workingHours: string;
  followLinks?: {
    facebookUrl?: string | null;
    instagramUrl?: string | null;
    tiktokUrl?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: string;
  brandName: string;
  description: string;
  links: {
    facebookUrl: string;
    email: string;
    phone: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "register".
 */
export interface Register {
  id: string;
  title: string;
  description: string;
  gradeLabel: string;
  subjects?:
    | {
        title: string;
        icon: 'book' | 'languages' | 'calculator' | 'atom' | 'globe' | 'code' | 'music' | 'palette' | 'flask' | 'dna';
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "timetable".
 */
export interface Timetable {
  id: string;
  title: string;
  description: string;
  availableGrades?:
    | {
        value: 'S1' | 'S2' | 'S3' | 'S4' | 'S5' | 'S6' | 'F1' | 'F2' | 'F3' | 'F4' | 'F5';
        label: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero_select".
 */
export interface HeroSelect<T extends boolean = true> {
  description?: T;
  metrics?:
    | T
    | {
        parents?: T;
        students?: T;
        subjects?: T;
        tutors?: T;
      };
  carousel?:
    | T
    | {
        image?: T;
        alt?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about_select".
 */
export interface AboutSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  featureImage?:
    | T
    | {
        image?: T;
        alt?: T;
      };
  missionPoints?:
    | T
    | {
        card1?:
          | T
          | {
              title?: T;
              shortDescription?: T;
              longDescription?: T;
            };
        card2?:
          | T
          | {
              title?: T;
              shortDescription?: T;
              longDescription?: T;
            };
        card3?:
          | T
          | {
              title?: T;
              shortDescription?: T;
              longDescription?: T;
            };
      };
  stats?:
    | T
    | {
        stat1?:
          | T
          | {
              value?: T;
              label?: T;
            };
        stat2?:
          | T
          | {
              value?: T;
              label?: T;
            };
        stat3?:
          | T
          | {
              value?: T;
              label?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "why-us_select".
 */
export interface WhyUsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  features?:
    | T
    | {
        feature1?:
          | T
          | {
              icon?: T;
              title?: T;
              description?: T;
              expandedContent?: T;
            };
        feature2?:
          | T
          | {
              icon?: T;
              title?: T;
              description?: T;
              expandedContent?: T;
            };
        feature3?:
          | T
          | {
              icon?: T;
              title?: T;
              description?: T;
              expandedContent?: T;
            };
        feature4?:
          | T
          | {
              icon?: T;
              title?: T;
              description?: T;
              expandedContent?: T;
            };
        feature5?:
          | T
          | {
              icon?: T;
              title?: T;
              description?: T;
              expandedContent?: T;
            };
        feature6?:
          | T
          | {
              icon?: T;
              title?: T;
              description?: T;
              expandedContent?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "teachers_select".
 */
export interface TeachersSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  teachers?:
    | T
    | {
        name?: T;
        title?: T;
        description?: T;
        subjects?:
          | T
          | {
              label?: T;
              id?: T;
            };
        photo?:
          | T
          | {
              image?: T;
              alt?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subjects_select".
 */
export interface SubjectsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  categories?:
    | T
    | {
        primary?:
          | T
          | {
              subjects?:
                | T
                | {
                    title?: T;
                    icon?: T;
                    shortDescription?: T;
                    highlights?:
                      | T
                      | {
                          text?: T;
                          id?: T;
                        };
                    id?: T;
                  };
            };
        lowerSecondary?:
          | T
          | {
              subjects?:
                | T
                | {
                    title?: T;
                    icon?: T;
                    shortDescription?: T;
                    highlights?:
                      | T
                      | {
                          text?: T;
                          id?: T;
                        };
                    id?: T;
                  };
            };
        upperSecondary?:
          | T
          | {
              subjects?:
                | T
                | {
                    title?: T;
                    icon?: T;
                    shortDescription?: T;
                    highlights?:
                      | T
                      | {
                          text?: T;
                          id?: T;
                        };
                    id?: T;
                  };
            };
      };
  packages?:
    | T
    | {
        id?: T;
        name?: T;
        grade?: T;
        price?: T;
        subjects?:
          | T
          | {
              label?: T;
              id?: T;
            };
        popular?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact_select".
 */
export interface ContactSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  contactInfo?:
    | T
    | {
        phone?: T;
        email?: T;
        location?: T;
      };
  workingHours?: T;
  followLinks?:
    | T
    | {
        facebookUrl?: T;
        instagramUrl?: T;
        tiktokUrl?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  brandName?: T;
  description?: T;
  links?:
    | T
    | {
        facebookUrl?: T;
        email?: T;
        phone?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "register_select".
 */
export interface RegisterSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  gradeLabel?: T;
  subjects?:
    | T
    | {
        title?: T;
        icon?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "timetable_select".
 */
export interface TimetableSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  availableGrades?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}